server:
    port: 9000



spring:

    #????
#    profiles:
#        active: prod

    datasource:
        druid:
            name: challengecup
            url: jdbc:mysql://localhost:3306/challengecup?serverTimezone=UTC
            username: root
            password: 123456
            driver-class-name: com.mysql.jdbc.Driver  #???????


mybatis-plus:

    global-config:
        db-config:
            #      id??
            id-type: auto
    configuration:
        log-impl: org.apache.ibatis.logging.stdout.StdOutImpl  #????? SQL ????
        map-underscore-to-camel-case: true #??????????